spring:
  application:
    name: api-service
  datasource:
    url: jdbc:postgresql://localhost:5432/transit
    username: transit
    password: transit
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

redis:
  host: localhost
  port: 6379

server:
  port: 8080
